// Shared content for the Spectrum personal site. English-only.
// Paul wird die Inhalte später konkret ersetzen — Struktur ist hier festgelegt.

window.PK_PALETTE = {
  pink:    '#f72585',
  plum:    '#b5179e',
  indigo:  '#7209b7',
  ultra:   '#560bad',
  azure:   '#480ca8',
  royal:   '#3a0ca3',
  persian: '#3f37c9',
  sapph:   '#4361ee',
  sky:     '#4895ef',
  aqua:    '#4cc9f0',
};

window.PK_CONTENT = {
  name: 'Paul Kern',
  handle: 'paulkern',
  role: 'Software Engineer & Physical Simulation Researcher',
  location: 'Germany',
  status: 'Currently open to working-student & internship roles from Q3.',
  intro: [
    'Hi — I\u2019m Paul. I build software for both research and production across geometry processing, computer graphics, and physical simulation.',
    'For the past few years my focus has been computer graphics and geometry processing — contributing to research projects and software collaborations. More recently I\u2019ve taken a keen interest in physics simulation; my master\u2019s thesis builds on the Wave Curves paper by Tomáš Skřivan et al. and explores methods for simulating fine wave detail on fluid simulations.',
    'When I\u2019m not coding I\u2019m usually on a hike, climbing, or talking about life with friends.',
  ],
  sectionLabels: {
    about:    'About',
    career:   'Career',
    projects: 'Projects',
    research: 'Research',
    skills:   'Skills',
    hobbies:  'Hobbies',
    contact:  'Contact',
  },
  career: [
    {
      kind: 'work',
      range: '06/2024 — now',
      role: 'Research Assistant',
      org:  'Chair for Geometry Processing · RWTH Aachen (Prof. Kobbelt)',
      body: '',
      tags: [],
    },
    {
      kind: 'edu',
      range: '10/2024 — now',
      role: 'M.Sc. Computer Science',
      org:  'RWTH Aachen University',
      body: 'Focus on physically-based simulation and animation.',
      tags: [],
    },
    {
      kind: 'work',
      range: '06/2024 — 05/2026',
      role: 'Software Developer',
      org:  'Auto-Koch GmbH & Co. KG',
      body: 'Developed KoKi — an internal management platform that unifies customer and vehicle records, with workflows tailored to Auto-Koch’s day-to-day operations.',
      tags: [],
    },
    {
      kind: 'edu',
      range: '10/2020 — 05/2024',
      role: 'B.Sc. Computer Science',
      org:  'RWTH Aachen University',
      body: 'Focus on geometry processing and computer graphics. Thesis at the Chair for Geometry Processing (Prof. Kobbelt): “Hash-Based Octrees for Offset Mesh Generation”.',
      tags: [],
    },
    {
      kind: 'extra',
      range: '02/2018',
      role: 'Jugend forscht — Regional Competition',
      org:  'Northwest Saxony · Youth research competition',
      body: '',
      tags: [],
    },
    {
      kind: 'edu',
      range: '08/2017 — 10/2020',
      role: 'Abitur (Higher Education Entrance Qualification)',
      org:  'Arwed-Roßbach-Schule · Leipzig',
      body: 'Advanced courses: Computer Science and Mathematics.',
      tags: [],
    },
    {
      kind: 'edu',
      range: '09/2011 — 06/2017',
      role: 'Secondary School',
      org:  'Bertolt Brecht School · Zöschen',
      body: '',
      tags: [],
    },
    {
      kind: 'edu',
      range: '09/2007 — 07/2011',
      role: 'Primary School',
      org:  'Thomas Münzer Grundschule · Kötzschau',
      body: '',
      tags: [],
    },
  ],
  projects: [
    {
      year: '2026',
      title: 'Fracturing',
      desc: 'Collaboration with Prof. Chad Landis’ group: developing a custom-tailored quad remeshing algorithm for their FEM-based fracture simulation. Source private.',
      tags: ['C++', 'Fortran', 'polymesh'],
      hue: 320,
      private: true,
    },
    {
      year: '2025',
      title: 'Mesh Kernel',
      desc: 'Reference implementation accompanying the paper “Exact and Efficient Mesh-Kernel Generation”. Source not yet public.',
      tags: ['C++', 'polymesh', 'Python', 'Bash'],
      hue: 200,
      private: true,
    },
    {
      year: '2025',
      title: 'Auto-Linker',
      desc: 'Obsidian plugin that automatically detects unlinked notes and links them.',
      tags: ['JavaScript', 'Obsidian'],
      hue: 0,
      href: 'https://github.com/conixtract/auto-linker',
    },
    {
      year: '2025',
      title: 'Minesweeper',
      desc: 'A Minesweeper clone built as a first project to learn Rust.',
      tags: ['Rust'],
      hue: 40,
      href: 'https://github.com/conixtract/minesweeper',
    },
    {
      year: '2024',
      title: '44Bars',
      desc: 'Personal NixOS and Debian configuration — desktop, dotfiles and ricing setup.',
      tags: ['Nix', 'Bash', 'CSS', 'HTML'],
      hue: 160,
      href: 'https://github.com/conixtract/44Bars',
    },
    {
      year: '2024',
      title: 'Hash-Based Octree',
      desc: 'C++ hash-based octree built as part of my bachelor thesis. Source not yet public.',
      tags: ['C++'],
      hue: 240,
      private: true,
    },
    {
      year: '2024',
      title: 'Offset Mesh Generation',
      desc: 'Offset mesh generation pipeline written for my thesis project on top of polymesh.',
      tags: ['C++', 'polymesh'],
      hue: 280,
      private: true,
    },
  ],
  research: [
    {
      year: '2025',
      title: 'Exact and Efficient Mesh-Kernel Generation',
      venue: 'SGP 2025 · Computer Graphics Forum 44(5)',
      role: 'co-author',
      status: 'published',
      href: 'https://onlinelibrary.wiley.com/doi/full/10.1111/cgf.70187',
    },
  ],
  skills: [
    { cat: 'Spoken Languages',      items: ['German (native)', 'English (C1)'] },
    { cat: 'Programming Languages', items: ['C++', 'JavaScript', 'Python', 'Rust', 'GLSL', 'SQL' , 'Java', 'Pascal'] },
    { cat: 'Tools & Infra',         items: ['Linux', 'Nix', 'Git', 'Docker', 'LaTeX', 'Bash', 'CMake'] },
    { cat: 'Numerics & Simulation', items: ['SPH', 'FEM', 'PBD', 'Continuum Mechanics', 'Fluid Dynamics', 'Rigid Body Dynamics'] },
    { cat: 'Geometry Processing',   items: ['DDG', 'Mesh-Offsets', 'Mesh-Booleans', 'Quadmeshing'] },
  ],
  hobbies: [
    { t: 'Dancing',          d: 'Salsa LA & Cubana, West Coast Swing, Bachata.' },
    { t: 'Climbing',         d: 'Indoor & outdoor bouldering.' },
    { t: 'Side Projects',    d: 'Small tools, programs & ricing.' },
    { t: 'Hiking & Camping', d: 'Multi-day hikes & outdoor camping, 100 km+.' },
    { t: 'Video games',      d: 'Strategic, action, single & multiplayer, creative.' },
    { t: 'Billiard',         d: 'Casual with friends.' },
    { t: 'Movies & Series',  d: 'Animes, documentaries, social.' },
  ],
  contact: 'Get in touch.',
  featured: [
    {
      label: 'Research',
      handle: 'Exact Mesh-Kernel Generation',
      href:   'https://onlinelibrary.wiley.com/doi/full/10.1111/cgf.70187',
      hue:    200,
    },
    {
      label: 'Project',
      handle: '44Bars',
      href:   'https://github.com/conixtract/44Bars',
      hue:    320,
    },
  ],
  links: [
    { label: 'GitHub', href: 'https://github.com/conixtract',           handle: '@conixtract' },
    { label: 'ORCID',  href: 'https://orcid.org/0009-0007-0259-0242',   handle: '0009-0007-0259-0242' },
    { label: 'Email',  href: 'mailto:paul.kern1@rwth-aachen.de',        handle: 'paul.kern1@rwth-aachen.de' },
  ],
};
